### ISSUE TITLE
GNO-pi-ascendant — Use pi as the frontend for a stateful Ascendant

### ISSUE THREAD

**Issue by phynics** [phynics/Gnostic#73]
> **Status: Done.**
> Parent: #69 ([EPIC] Use pi as the frontend for an Ascendant) · Priority: P1 · Type: prototype work-plan
> Depends on: #70, #71, #74
> Artifact: https://github.com/phynics/gnostic-pi at reviewed commit `8382a20`, included in published `main`. Live broker smoke passed; serve-side tool invocation shipped in #83 (`c3ba18b`).

## Outcome

Register `gnostic/ascendant` as a **stateful-agent frontend adapter** so pi supplies the native CLI/TUI while the bound Ascendant Timeline supplies context, memory, and remote tool execution.

This deliberately uses pi's custom-provider seam for native user/assistant transcript UX. It is not a stateless LanguageModel provider and must not claim context/tool compatibility it does not implement.

## Turn semantics

For each ordinary pi prompt while `gnostic/ascendant` is selected:

1. `before_agent_start` captures the stable pi user-entry id and current Timeline binding.
2. Derive `clientTurnID = pi:<session-id>:<entry-id>` and retain it across retry/cancellation handling.
3. `streamSimple` extracts only the new user text; historical pi `Context` is intentionally ignored because the Ascendant Timeline is authoritative.
4. Call bridge `gnostic.ascendant.chat` with Ascendant id, Timeline id, clientTurnID, and message.
5. The Ascendant runs its own model/tool loop and returns final text.
6. Emit pi events: start → text_start → one text_delta → text_end → done.

Pi's transcript is a local mirror. Cross-provider handoff into the Ascendant does not import prior pi context in v1.

## Provider registration

- Static provider/model identity: provider `gnostic`, model `ascendant`, display name `Gnostic Ascendant`.
- Do not model Timelines as models; Timeline selection is extension/session state managed by #71.
- Register from the extension factory without starting resources; bridge startup remains in `session_start`.
- Provider call awaits bridge readiness/binding or returns an actionable provider error.
- Usage/cost is reported as unknown/zero unless the Ascendant wire result later exposes real usage.
- Text input only in v1; reject image content explicitly.

## Guardrails while selected

- Save pi's active tool set, then deactivate pi tools; the Ascendant owns the tool loop. Restore the exact prior set when switching away.
- Cancel `session_before_compact`; internal summarization must never become an Ascendant turn.
- Block `session_before_fork` and `session_before_tree` with a clear notification until Timeline clone/fork semantics exist.
- Forward `SimpleStreamOptions.signal` through JSON-RPC cancellation to Axoloty.
- Do not auto-resubmit with a new turn id. Any retry uses the same `clientTurnID` and relies on #74 replay.
- Prevent two active provider requests for one bound Timeline from bypassing the Ascendant's serialized turn coordinator.

## Failure behavior

- Missing/stale binding: fail with instructions to run `/gnostic-status` or `/gnostic-use`.
- Ascendant absent / Timeline missing: structured provider error; do not silently create a replacement Timeline.
- Cancellation: emit pi `aborted`; #74 defines whether the admitted remote turn completes/replays.
- Empty reply: return explicit `(empty reply)` compatibility text or a defined error—never end the pi stream with pending stop reason.
- Bridge crash: provider error; extension may restart bridge for a subsequent user action, but the same turn id must be retained for retry.

## Tests

Adapt relevant pi provider suites/patterns:

- text event ordering and final assistant message;
- AbortSignal/cancellation;
- empty and Unicode output;
- same-turn retry uses the same clientTurnID;
- image input rejection;
- no pi tool definitions active in Ascendant mode;
- compaction/fork/tree guards;
- active tools restored when changing provider;
- new/resume Timeline binding behavior from #71;
- broker-backed end-to-end prompt where the Ascendant invokes an attached fixture tool and pi displays final text.

## Acceptance criteria

- [x] Selecting `gnostic/ascendant` makes pi a frontend for the bound stateful Ascendant Timeline.
- [x] The Ascendant—not pi context—owns prior conversation and workspace-tool execution.
- [x] Pi displays native user and assistant messages without recreating `gnostic chat`'s REPL.
- [x] Retry/cancellation cannot duplicate a Timeline turn.
- [x] Pi tools, compaction, fork, and tree cannot silently create split ownership.
- [x] Switching away restores the previous pi tool configuration.
- [x] Timeline is session state, never represented as a model id.

## Non-goals

- No true stateless/cross-provider-compatible LanguageModel contract.
- No image turns.
- No Timeline history hydration, clone, or fork.
- No token streaming from the Ascendant in v1.

**Comment by phynics** [comment]
Implementation started after #70/#74 completion and #71 foundation review. Work will extend the standalone pi extension repository at `/home/atakan/.pi/agent/extensions/gnostic` on an isolated issue branch; no plan/spec/ticket files will be added.

**Comment by phynics** [comment]
Implementation checkpoint: commit `6c1003d` on `codex/73-ascendant-provider` adds the `gnostic/ascendant` provider adapter in the standalone extension repository.

Validation:
- 11 passing Node tests, including text-only input, image rejection, stable provider lifecycle, and pi-tool restoration.
- `pi --offline --no-session --extension .../index.ts --list-models gnostic` exposes `gnostic/ascendant`.
- End-to-end pi print-mode smoke with the deterministic fake bridge returns `Echo from fake Ascendant`.

The branch is isolated and not pushed or merged.

**Comment by phynics** [comment]
> **Tracker update (2026-08-10):** moved to **In review** after hardening commit `8382a20` on branch `codex/73-ascendant-provider` in the standalone extension repository.
>
> Validation: 14/14 Node tests pass (bridge, lifecycle, cancellation, stream ordering, empty replies, per-Timeline overlap exclusion, and preselected-model ownership); `node --experimental-strip-types --check index.ts`; pi `--list-models gnostic`; and real pi end-to-end smoke through the deterministic fake bridge (`Echo from fake Ascendant`).
>
> Independent review findings were addressed: immutable per-turn binding snapshots, per-Timeline in-flight exclusion, correct partial-message sequencing, explicit empty-reply compatibility text, and session-start provider ownership synchronization. Live broker smoke and publishing/PR integration remain follow-up review work.

**Comment by phynics** [comment]
Publication update: reviewed provider commit 8382a20 is now included in the published https://github.com/phynics/gnostic-pi main branch. The issue remains In review; live broker-backed validation is still outstanding.

**Comment by phynics** [comment]
Live broker checkpoint: the published pi extension launched exactly one bridge connection with automatic extension loading disabled, selected the live advertised Timeline, sent a real gnostic/ascendant turn through MQTT to configured gnostic serve, and displayed exact final text `LIVE_OK`; the bridge child exited afterward. `make verify` passed 148 tests, `make bridge-smoke` passed, and `make runner-smoke` passed. The remaining acceptance gap is an attached served Workspace tool: standalone ServeRuntime advertises workspace_echo but does not register its WorkspaceProvider, so the existing bridge smoke logs tool execution failure. #82 now owns that production bug and blocks closure of this ticket.

**Comment by phynics** [comment]
Final live tool-loop validation passed on #83: the served Workspace was attached through the real bridge/MQTT path; direct workspace_echo returned LIVE_TOOL_OK; then published pi with gnostic/ascendant asked the configured remote Ascendant to invoke workspace_echo, ServeRuntime logged successful local execution, and pi displayed TOOL_LOOP_OK. The deterministic bridge smoke now also verifies the successful tool result reaches the model. This ticket is acceptance-complete and can close when #83 merges.

**Comment by phynics** [comment]
Completed after #83 merged as c3ba18b. Final live evidence: published pi selected gnostic/ascendant, bound the advertised Timeline, invoked attached workspace_echo through the real bridge/MQTT/ServeRuntime path, and displayed TOOL_LOOP_OK. Deterministic and full gates are green.

**Comment by phynics** [comment]
Superseded as the implementation target by the ACP migration in #84. Its stateful Ascendant conclusions remain valid, but the custom bridge and Gnostic-specific Pi extension move to `gnostic acp` and `phynics/pi-acp-client` respectively.
